---
title: "Python Visualization"
author: "ryan.benac"
date: "`r Sys.Date()`"
output: html_document
---

Libraries
```{r setup}
library(plotly)
library(ggplot2)
#library(reticulate) # r python

# reticulate grabs the first version of R it can find that contains the first module it will import
#pandas <- import("pandas")


```


```{python}
import plotly.express as px
import plotly.offline as py

df = px.data.gapminder()
plot = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])

plot.show()
#py.plot(plot,filename = 'test.html', auto_open = False)

```

```{r, echo=FALSE}
# this will show the saved html file
#htmltools::includeHTML("test.html")
```

```{r}
df <- data.frame(
  x = c(1,2,3,4), 
  y = c(1,2,3,4), 
  f = c(1,2,3,4)
)

p <- ggplot(df, aes(x, y)) +
    geom_point(aes(frame = f))

ggplotly(p)
```

```{r}
library(plotly)
fig <- plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
fig
```

```{r}

```

```{r}

```

```{r}

```
